#!/usr/bin/env python3
"""Generates the website's _bibliography/papers.bib (eneamanzi.github.io) from
this repo's single source of truth in data/60-publications.json.

Each publication's "bibtex" field is the citation text as-is (hand-written
while a paper is only submitted, or copied verbatim from the publisher once
it's indexed somewhere) - this script does not parse or reconstruct BibTeX
from separate fields (authors/venue/year/...), it only concatenates what's
already there and, if present, injects one extra field: "venueAbbr" becomes
an `abbr = {...}` line, which al-folio's bib.liquid layout uses to render a
venue badge (see _data/venues.yml on the website side for the badge's
color/link - not generated here, see validate_venues.py).

Usage: python3 scripts-website-data/generate_papers_bib.py <output-path>
"""

import json
import os
import re
import sys

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

# IMPORTANT: do not put any `%`-commented BibTeX-shaped example (a fake
# `@type{key, field=value}` block) in this header, however harmless it looks.
# Verified empirically (real `docker compose` build, bibtex-ruby 6.2.0 via
# jekyll-scholar 7.3.0): a `%`-commented entry - even a single short one - is
# NOT actually inert to this parser and crashes the whole Jekyll build with a
# BibTeX::ParseError (surfaced as a confusing "unhandled exception" from
# Jekyll::Cache under some Ruby versions). A plain comment with no `@{...}`
# shape, like this one, is safe. See CUSTOMIZATIONS.md > Publications for the
# full incident writeup and the field reference (selected, preview, etc.).
HEADER = """\
% AUTO-GENERATED by generate_papers_bib.py in the Curriculum-Vitae repo.
% Do not add real entries directly here - they are overwritten on every push
% to data/60-publications.json. Add them there instead (as a "bibtex" field).
%
% Extra fields the website's bib.liquid layout understands, beyond the
% standard BibTeX ones (title/author/year/journal/booktitle/school/month/
% note/location) - add any of these directly inside a publication's "bibtex"
% text in data/60-publications.json when you have the real value for it.
% None of these are required - the site just skips whatever is missing.
%   abbr              - short venue label shown as a colored badge (needs a matching entry in the website's _data/venues.yml)
%   abstract          - "Abs" button revealing the abstract text (already handled automatically, see above)
%   preview           - filename (in assets/img/publication_preview/) or URL of a preview image shown next to the entry
%   award / award_name - "Awarded"/award-name button + expandable box with markdown text
%   doi               - "DOI" button linking to doi.org/<value>
%   arxiv             - "arXiv" button linking to the arXiv abstract page
%   hal               - "HAL" button (French HAL open archive)
%   bibtex_show       - "Bib" button revealing the raw BibTeX text
%   html              - "HTML" button (local file under assets/html/, or external URL)
%   pdf               - "PDF" button (local file under assets/pdf/, or external URL)
%   supp              - "Supp" button, supplementary material (local assets/pdf/ or external URL)
%   poster / slides   - "Poster"/"Slides" buttons (local assets/pdf/ or external URL)
%   video             - "Video" button (embedded player if enable_video_embedding is on in _config.yml, else opens the link)
%   blog              - "Blog" button linking to a blog post about the paper
%   code              - "Code" button linking to a code repository
%   website           - "Website" button linking to a project website
%   altmetric / dimensions / google_scholar_id / inspirehep_id - citation-metric badges (need the real external ID)
%   eprint / pmid / isbn - fallback identifiers used by the altmetric/dimensions badges
%   annotation        - small (i) info icon with a popover note
%   additional_info   - free markdown text appended after the venue/year line
%   selected          - also show this paper in the "selected publications" list on the About page (also requires selected_papers: true in the website's _pages/about.md)
"""


def read_publications():
    path = os.path.join(DATA_DIR, "60-publications.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def en(node):
    return node["en"] if isinstance(node, dict) else node


def inject_fields(bibtex, fields):
    """Inserts extra `name = {value},` lines right after the opening
    `@type{key,` line, so the hand-written/copied citation text itself is
    never touched. Skips a field if it's already present in the text (e.g. a
    publisher-provided citation already carries its own abstract) or if its
    value is falsy - never introduces a duplicate/empty BibTeX field."""
    first_line, rest = bibtex.split("\n", 1)
    lines_to_insert = [
        f"  {name} = {{{value}}},"
        for name, value in fields.items()
        if value and not re.search(rf"^\s*{re.escape(name)}\s*=", bibtex, re.MULTILINE)
    ]
    if not lines_to_insert:
        return bibtex
    return first_line + "\n" + "\n".join(lines_to_insert) + "\n" + rest


def build():
    entries = [
        inject_fields(pub["bibtex"], {"abbr": pub.get("venueAbbr"), "abstract": en(pub["abstract"])})
        for pub in read_publications()
    ]
    return HEADER + "\n" + "\n\n".join(entries) + "\n"


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 scripts-website-data/generate_papers_bib.py <output-path>", file=sys.stderr)
        sys.exit(1)
    output_path = sys.argv[1]
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(build())
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
