#!/usr/bin/env python3
"""Generates the website's _data/socials.yml (eneamanzi.github.io) from this
repo's single source of truth in data/10-personal.json.

Only the fields that are genuine CV facts (email, LinkedIn/GitHub usernames,
CV PDF path) are generated. The other jekyll-socials fields (scholar_userid,
wechat_qr, whatsapp_number, custom_social, ...) have no CV equivalent and are
left as commented-out documentation, same as the file's original template -
add them by hand in the website repo if you ever start using one.

Usage: python3 scripts/generate_socials_yml.py <output-path>
"""

import json
import os
import sys

from pydantic import BaseModel, ConfigDict, Field

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


class Socials(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cv_pdf: str = Field(min_length=1)
    email: str = Field(min_length=1)
    linkedin_username: str = Field(min_length=1)
    github_username: str = Field(min_length=1)

# Stable site convention (matches _pages/cv.md's own cv_pdf front matter) - not
# a CV fact, so not read from data/10-personal.json.
CV_PDF_PATH = "/assets/pdf/cv_english.pdf"


def read_data(filename):
    with open(os.path.join(DATA_DIR, filename), encoding="utf-8") as f:
        return json.load(f)


def find_username(profiles, network):
    for prof in profiles:
        if prof["network"] == network:
            return prof["username"]
    return None


def build():
    p = read_data("10-personal.json")

    # Fails loudly (pydantic.ValidationError) instead of silently writing the
    # literal string "None" into the YAML if a network is missing/renamed.
    socials = Socials(
        cv_pdf=CV_PDF_PATH,
        email=p["email"],
        linkedin_username=find_username(p["profiles"], "LinkedIn") or "",
        github_username=find_username(p["profiles"], "GitHub") or "",
    )

    return f"""\
# AUTO-GENERATED by generate_socials_yml.py in the Curriculum-Vitae repo.
# Do not edit cv_pdf/email/linkedin_username/github_username directly here -
# they are overwritten on every push to data/10-personal.json. Edit that file
# instead. The commented-out fields below have no CV equivalent and are safe
# to uncomment/edit by hand.
#
# this file contains the social media links and usernames of the author
# the socials will be displayed in the order they are defined here
# for more information, please refer to the documentation of jekyll-socials plugin: https://github.com/george-gca/jekyll-socials
cv_pdf: {socials.cv_pdf} # path to your CV PDF file
email: {socials.email} # your email address
linkedin_username: {socials.linkedin_username} # your linkedin username
github_username: {socials.github_username} # your github username
# inspirehep_id: 1010907 # Inspire HEP author ID
# rss_icon: true # comment this line to hide the RSS icon (disabled: blog is off, feed would be empty)
# scholar_userid: qc6CJjYAAAAJ # your Google Scholar ID
# wechat_qr: # filename of your wechat qr-code saved as an image (e.g., wechat-qr.png if saved to assets/img/wechat-qr.png)
# whatsapp_number: # your WhatsApp number (full phone number in international format. Omit any zeroes, brackets, or dashes when adding the phone number in international format.)
# custom_social: # can be any name here other than the ones already defined in the jekyll-socials plugin
#   logo: https://www.alberteinstein.com/wp-content/uploads/2024/03/cropped-favicon-192x192.png # can be png, svg, jpg
#   title: Custom Social
#   url: https://www.alberteinstein.com/
"""


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/generate_socials_yml.py <output-path>", file=sys.stderr)
        sys.exit(1)
    output_path = sys.argv[1]
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(build())
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
